{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "et-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- .Values.env.config | toYaml | nindent 2}}
---
{{- end}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "et-collector.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  collector.properties: |-
    takipi.listen.port=6070
    takipi.backend.url={{ .Values.et.backendURL }}
    takipi.storage.test.url={{ .Values.et.storageTestURL }}
