apiVersion: v1
kind: ConfigMap
metadata:
  name: et-collector-env
  namespace: {{ .Release.Namespace }}
data:
  JVM_HEAPSIZE: "{{ .Values.et.java.heapSize }}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: et-collector-config
  namespace: {{ .Release.Namespace }}
data:
  collector.properties: |-
    takipi.listen.port=6070
    takipi.backend.url={{ .Values.et.backendURL }}
    takipi.storage.test.url={{ .Values.et.storageTestURL }}
