apiVersion: v1
kind: Service
metadata:
  name: et-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "et-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "et-collector.selectorLabels" . | nindent 4 }}
